### PR TITLE
Bandaid for array observers issues.

### PR DESCRIPTION
**Pull request by arthurevans**
Related to Polymer/polymer#3239

### CODE REVIEW

**Comment by arthurevans** [comment]
cc: @mercmobily @kaste @kevinpschaaf

**Comment by kevinpschaaf** [comment]
LGTM

**Comment by mercmobily** [comment]
"the change record includes an addition property" -> the change record includes an additional property"

**Comment by arthurevans** [comment]
Thanks @mercmobily!

**Pull request merged**
