### PR TITLE
Update article for App Layout 2.0

### PR DESCRIPTION
**Pull request by keanulee**
cc @frankiefu @blasten @arthurevans

### CODE REVIEW

**Comment by keanulee** [comment]
Related: https://github.com/PolymerElements/app-layout/pull/351

**Comment by frankiefu** [comment]
https://github.com/Polymer/docs/pull/1777/files#diff-f5a993052c8f176667b8b44e7a567720R80
Change `<style is="custom-style">` to `<custom-style>`

**Comment by frankiefu** [comment]
LGTM

**Comment by blasten** [comment]
Looks good

**Pull request merged**
