### PR TITLE
Update setup and build instructions. 

### PR DESCRIPTION
**Pull request by kaycebasques**
* Updated and expanded the setup and build instructions in `README.md`.
* Changed `"grunt-vulcanize": "*"` to `"grunt-vulcanize": "^0.6.4"`. I believe the latest release, 1.0, released a couple days ago, breaks the build process. I'm not sure if there are repercussions to this for anyone else. 
* In the instructions I instruct the user to install all of the Ruby stuff into the user's home directory. The original instructions just say `gem install bundler` and `bundle install`, which defaults to the System directory of Ruby gems (and requires `sudo`). Installing to system can cause all sorts of problems and I think it's a bad practice that we do not want to encourage. 
* I also instruct them to install version 0.7 of `vulcanize` via `npm -g install vulcanize@0.7`. The original instructions just say `npm -g install vulcanize` which will install the latest (version 1.10), and I'm pretty sure this version also breaks the build process.

### CODE REVIEW

**Comment by kaycebasques** [comment]
A couple other things to note:
* In the instructions I instruct the user to install all of the Ruby stuff into the user's home directory. The original instructions just say `gem install bundler` and `bundle install`, which defaults to the System directory of Ruby gems (and requires `sudo`). Installing to system can cause all sorts of problems and I think it's a bad practice that we do not want to encourage. 
* I also instruct them to install version 0.7 of `vulcanize` via `npm -g install vulcanize@0.7`. The original instructions just say `npm -g install vulcanize` which will install the latest (version 1.10), and I'm pretty sure this version also breaks the build process.

**Comment by robdodson** [comment]
LGTM.

**Comment by kaycebasques** [comment]
R: @ebidel

**Comment by ebidel** [comment]
LGTM

**Pull request merged**
