### PR TITLE
Typo in {{site.project_title}}

### PR DESCRIPTION
**Pull request by lemabu**
{{site.project.title}} should be {{site.project_title}}

### CODE REVIEW

**Comment by lemabu** [comment]
CLA signed.

**Comment by arthurvr** [comment]
This looks good to me though there's a merge conflict.

**Comment by arthurevans** [comment]
Merge conflict is because the file's been moved to 1.0.

**Comment by lemabu** [comment]
I created (unless I messed up) a new pull request against 1.0 ( https://github.com/Polymer/docs/pull/1131 )

**Comment by addyosmani** [comment]
Closed via https://github.com/Polymer/docs/pull/1131

**Pull request closed without merging**
