### PR TITLE
some typo

### PR DESCRIPTION
**Pull request by loctauxphilippe**

### CODE REVIEW

**Comment by loctauxphilippe** [comment]
I signed it!

**Comment by ebidel** [comment]
LGTM. Thanks!

**Comment by loctauxphilippe** [comment]
@ebidel You're welcome! But what does mean "LGTM"?

**Comment by ebidel** [comment]
Looks good to me.

**Comment by loctauxphilippe** [comment]
@ebidel oh ok! Thanks! :-)

**Pull request merged**
