### PR TITLE
remind readers that this.fooBar fires foo-bar-changed not fooBar-changed

### PR DESCRIPTION
**Pull request by drewp**

### CODE REVIEW

**Comment by ebidel** [comment]
LGTM. Just need you to sign the cla.

**Comment by gaurav21r** [comment]
@drewp Looks good +1. Why aren't you signing the CLA? Simple enough process!

**Comment by drewp** [comment]
Submitted again. Also https://github.com/Polymer/docs/pull/1245#issuecomment-118867954 and https://github.com/Polymer/docs/pull/1291#issuecomment-129495486

I signed it!

**Comment by addyosmani** [comment]
Manually verified @drewp is a Googler and has signed. PR LGTM. Thanks Drew!

**Pull request merged**
