### PR TITLE
Update firebase.json rewrite example. Fixes #1755

### LINKED ISSUE #1755: firebase.json rewrite property is wrong for polymer
Here https://www.polymer-project.org/1.0/start/toolbox/deploy
in the docs it says the correct way to configure firebase.json to host from firebase:

```
"rewrites": [ {
  "source": "**/!{*.*}",
  "destination": "/index.html"
} ]
```

but it does not work, and you will see 404 for any route other than root. Correct way is:

```
"rewrites": [ {
  "source": "**/!(*.*)",
  "destination": "/index.html"
} ]
```

### PR DESCRIPTION
**Pull request by robdodson**
@arthurevans PTAL

### CODE REVIEW

**Comment by abdonrd** [comment]
@robdodson maybe add the `__` for the Firebase Auth?

**Comment by robdodson** [comment]
good call

**Comment by robdodson** [comment]
ack yeah I'm just not sure if the `__` uses the same syntax...

**Comment by robdodson** [comment]
ok I decided to just do 2 rewrites just to be safe. @mbleigh does this change look ok to you?

**Comment by robdodson** [comment]
@arthurevans I think we might be good to merge

**Comment by abdonrd** [comment]
Hum... We should copy/paste to [Polymer/docs/app/2.0/start/toolbox/deploy.md](https://github.com/Polymer/docs/blob/master/app/2.0/start/toolbox/deploy.md)?

**Comment by robdodson** [comment]
yuuup

**Pull request merged**
