### PR TITLE
Fix possible small typo in v1 and v2 docs

### PR DESCRIPTION
**Pull request by petrpacas**
This could also be a misunderstanding on my part, so please check

### CODE REVIEW

**Comment by petrpacas** [comment]
I signed it!

**Comment by arthurevans** [comment]
Thanks for the PR! Our style is not to use possessives with product names, so the decision to avoid "Polymer's" is a conscious one.

**Comment by petrpacas** [comment]
Ok, roger that.
(You are using "Polymer's" troughout the docs tho)

**Comment by arthurevans** [comment]
Yep, you're right, we have more than I thought. O, for an editor!
Will try to clean some of those up!

**Pull request closed without merging**
