### PR TITLE
document strip-whitespace, fixes #1446

### LINKED ISSUE #1446: Document: strip-whitespace for small perf gain on templates
https://github.com/Polymer/docs/blob/968dbeae498bf113aeeb79aa10249a33ca7e267c/1.0/docs/release-notes.md#release-122-2015-11-12

### PR DESCRIPTION
**Pull request by kaycebasques**
@arthurevans ptal

### CODE REVIEW

**Comment by arthurevans** [comment]
Looks good to me, except that this should really be in `local-dom.md`, which deals with the local DOM template, rather than the (poorly-named) `templates.md`, which discusses the template helper elements, `dom-if`, `dom-repeat` and so on.

**Comment by arthurevans** [comment]
@sorvell @ebidel anything to add on the text here?

**Comment by kaycebasques** [comment]
@arthurevans moved the content to `local-dom.md`

**Comment by arthurevans** [comment]
LGTM.

**Pull request merged**
