### PR TITLE
Fix footer on doc pages.

### PR DESCRIPTION
**Pull request by ashi009**
This is a fix after #1581, which restores footer on doc pages to normal.

### CODE REVIEW

**Comment by arthurevans** [comment]
Can you explain what issue this PR is solving? I don't know what to look for in testing it.

**Comment by ashi009** [comment]
This fixes the footer on https://www.polymer-project.org/1.0/docs/devguide/feature-overview.html and all other doc pages.

**Comment by robdodson** [comment]
I think it just gives more padding so the social buttons are better vertically centered

**Comment by ashi009** [comment]
Indeed.  I've tested on different screen sizes, all looks good to me.

**Comment by arthurevans** [comment]
Okey doke.

**Pull request merged**
