### PR TITLE
Element pages

### PR DESCRIPTION
**Pull request by robdodson**
Not ready for review yet, just wanted to setup the PR so I could keep track of TODOs. I'll rebase and clean it up when it's ready.

---

### TODO

- [x] Inherited properties
- [x] Rename parent* to extended in element JSON
- [x] Add collapsed inherited sections
- [x] Make sure deep link scrolling still works
- [x] Menu should link to element pages instead of hash urls
- [x] Add grunt-doc-merge to build
- [x] Get download and demo buttons working again
- [ ] Handle deep linking to an inherited/collapsed field :frowning:

### CODE REVIEW

**Comment by robdodson** [comment]
@ebidel @addyosmani @arthurevans this is a crazy huge commit, sorry about that. Most of it is JSON that you can skip over.

The summary is that there is a new grunt task, [`grunt-doc-merge`](https://github.com/robdodson/grunt-doc-merge) which runs the [`doc-merge`](https://github.com/robdodson/doc-merge) module. I need to document these better but, in a nutshell, `doc-merge` looks at a [`config.json` file](https://github.com/Polymer/docs/pull/888/files#diff-06b2d3b23dce96e1619d2b53d6c947ecR1) to figure out where all of your elements and mixins live. Then it runs `context-free-parser` over them all, merging in any inherited/mixed-in fields, and dumps it all to `_data/elements`.

When jekyll runs, it will use [this page generator](https://github.com/Polymer/docs/pull/888/files#diff-24d8d9c7b08b6d955a1b47f7978a5be0R1) combined with [this template](https://github.com/Polymer/docs/pull/888/files#diff-38d622036156445eb738091ac927fd50R1) to create a static page for each element.

Each page gets the element's JSON stamped onto it, and then [fed to the `component-docs` element when the page boots up](https://github.com/Polymer/docs/pull/888/files#diff-38d622036156445eb738091ac927fd50R15).

Also, the `component-docs` element now has buttons which will open/close `core-collapse` elements that contain all of the inherited/mixed-in fields.

One issue that I still have is that I need to get deep-linking working with collapsed fields, but I would like to treat that as a separate unit of work in order to get this merged in sooner so the element docs can start being crawled.

Please review and let me know your thoughts.

**Comment by ebidel** [comment]
Reviewed

**Comment by robdodson** [comment]
@ebidel @arthurevans @addyosmani the `doc_merge` task now takes a `prefix` array (currently containing `core` and `paper`) and generates its configuration with that. I need to write docs but after that I think we're ready to merge.

**Comment by addyosmani** [comment]
Thanks for updating @robdodson. This currently needs to be rebased against master fyi.

**Comment by addyosmani** [comment]
Going to review and land #905 before we bring in the element pages changes. SGTY, @robdodson?

**Comment by robdodson** [comment]
@addyosmani cool

**Comment by addyosmani** [comment]
@robdodson Want to get this rebased up against master and we'll review before landing?

**Comment by ebidel** [comment]
Merging might be safer!

**Comment by robdodson** [comment]
Conflicts are cleaned up but not ready for merge yet. I need to retool the way the page generator works to deal with multiple versions

**Comment by robdodson** [comment]
@ebidel @addyosmani ok I've got everything working with the version switcher setup. I also encountered a problem with element descriptions having closing `</script>` tags and that conflicting with `replaceScriptTagWithRunnableScript` in `app.js`. But I think I've got it all sorted now.

One issue that remains is the [core-list guide](https://www.polymer-project.org/docs/elements/core-list.html) is now using the same URL as the core-list element doc. I could either put an exception in the page generator to have it create a special doc page for core-list, maybe `core-list-element.html` or something, or we could change the URL for the core-list guide, though that may annoy the Googles for a bit. wdyt?

**Comment by arthurevans** [comment]
The guide is relatively new, I say we just annoy the googles for awhile and
move the guide to core-list-guide.

**Comment by addyosmani** [comment]
> ok I've got everything working with the version switcher setup. I also encountered a problem with element descriptions having closing </script> tags and that conflicting with replaceScriptTagWithRunnableScript in app.js. But I think I've got it all sorted now.

:+1: 

> The guide is relatively new, I say we just annoy the googles for awhile and
move the guide to core-list-guide.

I'm fine with this. @robdodson do you want to move ahead with rebasing?

**Comment by robdodson** [comment]
OK! I think this is it. If @ebidel @addyosmani and @arthurevans can give it a trial run I would appreciate it. If it looks good to you folks I can rebase and merge in

**Comment by ebidel** [comment]
Reviewed

**Comment by robdodson** [comment]
@ebidel I removed the `postInstall`, ignored the generated files, and moved the listeners to `app.js`. Mind taking another look?

**Comment by ebidel** [comment]
Yay :fireworks:

**Comment by ebidel** [comment]
@robdodson I get

    jekyll 2.5.3 | Error:  comparison of Jekyll::Page with Jekyll::ElementPage failed

when running `grunt docs` are you on the latest?

**Comment by robdodson** [comment]
yeah I'm on jekyll 2.5.3 as well

**Pull request merged**
