### PR TITLE
Rename carbon-route and friends to app-*

### PR DESCRIPTION
**Pull request by rictic**
Part of https://github.com/PolymerElements/app-route/issues/100

### CODE REVIEW

**Comment by rictic** [comment]
Should we include a note in the article that it used to be called carbon-route?

**Comment by arthurevans** [comment]
Yes, we should definitely include a note up front, especially since it was published with the old names. I would say,

`<carbon-route>` and `<carbon-location>` have been renamed to `<app-route>` and `<app-location>` with release 0.9.0. This article has been updated with the new names. Or words to that effect.

**Comment by rictic** [comment]
Added a note about the renaming

**Comment by arthurevans** [comment]
Already fixed in the new site.

**Pull request closed without merging**
