### PR TITLE
Update footer.html

### PR DESCRIPTION
**Pull request by blissfulyoshi**
Prevent tab navigation from going to both outside a tag and paper-button by blocking tabbing from getting to outside a tag.

### CODE REVIEW

**Comment by arthurevans** [comment]
Apologies for the late response. Thanks for the PR!

**Comment by ebidel** [comment]
This is good! Mind updating the reset of the `<a>` wrapped paper-buttons on https://raw.githubusercontent.com/Polymer/docs/master/1.0/index.md as well? If not, no sweat. We can merge this as is.

**Comment by blissfulyoshi** [comment]
Okay, I think I added the fix to all the <a> wrapped paper-buttons on https://raw.githubusercontent.com/Polymer/docs/master/1.0/index.md

**Comment by ebidel** [comment]
Thanks!

**Pull request merged**
