### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by saniljhaveri**

### CODE REVIEW

**Comment by ebidel** [comment]
This introduces a typo. Not sure we want that :)

**Comment by saniljhaveri** [comment]
hey i am trying to make a web interface using Polymer paper elements and Google-sheets i am unable to make it work  as i have not worked with such api's before. where can i get to know more example for my applications ?

**Comment by ebidel** [comment]
Start here: https://www.polymer-project.org/docs/start/creatingelements.html.thatalso points to our tutorial dev guide, which is a working app.

**Comment by saniljhaveri** [comment]
thank you !

**Pull request closed without merging**
