### PR TITLE
Add using elements to nav

### PR DESCRIPTION
**Pull request by ebidel**
R: @robdodson @addyosmani @kaycebasques

### CODE REVIEW

**Comment by robdodson** [comment]
I think this is a good change. Is there any way to add an external page icon or will that involve a lot of pain?

**Comment by ebidel** [comment]
We can think about that in another CL? All external links could have it.

**Comment by robdodson** [comment]
ok sounds good

**Comment by kaycebasques** [comment]
The title in the navigation menu does not match the title of the document. I'll push a commit to this branch to fix this.

**Comment by kaycebasques** [comment]
There is a typo in the new "Get elements" dropdown menu. "Browser Element Catalog" --> "Browse Element Catalog". I'll fix it.

**Comment by kaycebasques** [comment]
The new dropdown panel ("Get elements") is a little off:

1. The topic of "Creating reusable elements" is not related to the parent topic of "Get elements" so it shouldn't be nested there.

2. We have two links to the catalog, one nested under "Get elements" and the other at the bottom of the top-level navigation menu. That seems weird.

**Comment by kaycebasques** [comment]
@ebidel see #1259 for my proposed changes. I moved "Create reusable elements" up a level. 

Having two outbounds links under "Get elements" seems off to me. I was trying to figure out how to address that but I've got nothing. I don't want to hold up the show on your stuff, so we can close this and I'll think about that topic for a later date.

**Comment by ebidel** [comment]
So can I merge this. Then we'll look at yours?

**Comment by kaycebasques** [comment]
Recommend reviewing mine, merging it into this branch, then merging this branch into master.

**Comment by addyosmani** [comment]
Moving 'Create reusable elements' up a level makes sense as it doesn't quite belong in 'Get elements'. @kaycebasques is the specific change you were requesting a look at this one https://github.com/Polymer/docs/commit/1bea29b8108ca6dcc3eeebcaae35373e590886e3?

**Comment by ebidel** [comment]
Done

**Comment by ebidel** [comment]
I'm not going to mess with merging other PRs into this one. If there are additional changes you're proposing, please open a new PR for them.

**Comment by kaycebasques** [comment]
LGTM

**Pull request merged**
