### PR TITLE
Add note about dom-if adding spans

### PR DESCRIPTION
**Pull request by esprehn**

### CODE REVIEW

**Comment by arthurevans** [comment]
Is this an expected effect of the `<template>` tag? Or something introduced by dom-bind? (And if the latter, is it something that's likely to change at any point?)

**Comment by addyosmani** [comment]
@arthurevans afaik this is dom-bind/Polymer's autobinding system and not expected of raw template. Changes LGTM minus one minor nit @esprehn

**Comment by addyosmani** [comment]
Friendly ping @esprehn

**Comment by arthurevans** [comment]
Will merge and munge.

**Comment by arthurevans** [comment]
Well, crap. I merged this, then I tested and... it appears to no longer be the case. Sigh.

**Pull request merged**
