### PR TITLE
[#916] Added valueattr to paper-tabs example

### PR DESCRIPTION
**Pull request by Nevraeka**
simple attribute add

### CODE REVIEW

**Comment by arthurevans** [comment]
This is a little confusing, but `valueattr` actually defaults to 'name', so this is unnecessary. See `valueattr` docs here:

https://www.polymer-project.org/docs/elements/core-elements.html#core-selector

**Comment by robdodson** [comment]
@arthurevans hm that is confusing, especially for a new user. Maybe we can modify the text a bit.

ex: "selected="all" chooses the first tab **with a matching `name` attribute** as the initially selected tab."

**Comment by Nevraeka** [comment]
I see what you mean

**Comment by Nevraeka** [comment]
:+1 @robdodson . I assume you are referring to the descriptive text, and not the code example. :)

**Comment by arthurevans** [comment]
Sounds good. Ironically, we used to have the valueattr attribute here, but
a prior PR removed it as unnecessary.

Will file a text PR this afternoon (and see if I can clarify the somewhat
vague docs for x-selector.

**Comment by Nevraeka** [comment]
Thanks @arthurevans . Should I cancel this PR then?

**Comment by robdodson** [comment]
Yeah I'm referring to the descriptive text in the tutorial

**Comment by ebidel** [comment]
Cleared up in https://github.com/Polymer/docs/commit/78a0acb6d3a3ec173db880b175ea19e8b8674bd7

**Pull request closed without merging**
