### PR TITLE
Fix highlighting, clean gulpfile, SW config/cache, and some styling

### PR DESCRIPTION
**Pull request by keanulee**

### CODE REVIEW

**Comment by keanulee** [comment]
@arthurevans @katejeffreys PTAL. You'll need to do a clean `rm -rf node_modules; npm i`

**Comment by katejeffreys** [comment]
I built from a fresh clone of the docs repo and am getting a bunch of errors.

I'm going to try building the master branch and see if the same thing happens.

```
ERROR    2017-11-06 22:04:03,574 wsgi.py:263] 
Traceback (most recent call last):
  File "/Users/katejeffreys/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/Users/katejeffreys/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/Users/katejeffreys/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "/Users/katejeffreys/docs/dist/server.py", line 24, in <module>
    import http2push.http2push as http2push
ImportError: No module named http2push.http2push
INFO     2017-11-06 22:04:03,577 module.py:813] default: "GET /?_sw-precache=7e354194f221428fb5049edf98c40dc7 HTTP/1.1" 500 -
INFO     2017-11-06 22:04:03,588 module.py:813] default: "GET /about?_sw-precache=1510a27b23b307f7e4c90ee068eda1d4 HTTP/1.1" 500 -
INFO     2017-11-06 22:04:03,589 module.py:813] default: "GET /app-shell.html?_sw-precache=1797bc4d743f133675cc064ea3040462 HTTP/1.1" 500 -
```

**Comment by arthurevans** [comment]
Tested and LGTM. Did we already remove the runtime highlighting?

**Comment by keanulee** [comment]
Yes, it was removed in https://github.com/Polymer/docs/commit/fa558d172cadb230165ef293cf40cd161e077ef0#diff-3d273d5b8b9c547209236c55141fcb88 (thankfully, since copying it from `node_modules/` to `bower_components/` was just plain ugly).

**Comment by keanulee** [comment]
Made a couple more commits to clean up that shouldn't really change anything. Please make sure it works for you and merge.

**Comment by arthurevans** [comment]
Retested, did very basic assessment on a few browsers. 

Seeing issues with Try Polymer on both Firefox and Safari (my IE VM isn't connected to the internet, so the samples wouldn't run at all there).

- Firefox is showing the sample code, but not showing anything in the output frames—as if the code isn't running. 

- Safari ironically is doing the _opposite_ thing—the output frames look fine, but the sample code is not shown. On page load, the sample code shows up for an instant and then collapses (so the tabs that show sample code are zero-height).

**Comment by keanulee** [comment]
To be specific, the previous commit was to workaround https://github.com/PolymerElements/iron-pages/issues/65, which is really a result of https://bugs.webkit.org/show_bug.cgi?id=179402

**Comment by arthurevans** [comment]
Tested, looks good now. Thanks!

**Pull request merged**
