### PR TITLE
@apply with parentheses is deprecated

### PR DESCRIPTION
**Pull request by rictic**
Noticed by Chad in `#2.0-preview` on slack

### CODE REVIEW

**Comment by arthurevans** [comment]
Does this form work in 1.0?

**Comment by rictic** [comment]
Yes, 1.0 works both with and without parens. 2.0 (at least at one point) only works without parens.

**Comment by rictic** [comment]
69fa975 LGTM assuming that the `{.alert .alert-info}` is something that is handled specially by the docs project.

**Comment by arthurevans** [comment]
Yeah, it gives us little alert/note boxes:

image

**Pull request merged**
