### PR TITLE
Updates behaviors.md fixes syntax

### PR DESCRIPTION
**Pull request by chuckh**
Changes `HighlightBehavior = {` TO `Polymer.HighlightBehavior = {`
Adds `<script></script>` for HighlightBehavior

### CODE REVIEW

**Comment by arthurevans** [comment]
Hi @chuckh,

This is intentionally not `Polymer.HighlightBehavior`. We attach behaviors to the `Polymer` object to avoid polluting the global namespace. (This is basically a stopgap until ES6 modules arrive.)

Since this is demonstrating a user-added behavior, it shouldn't be attached to `Polymer`. You can stick it on the global scope (as in the example), or create your own namespace.

**Comment by chuckh** [comment]
Hi @arthurevans,

Thanks for the clarification. I came across this while working on converting a mixin to behaviors on Road to Polymer. I removed the Polymer. and it still worked, but the behaviors file had to have <script></script> tags to work. So I think the docs should reflect this. I was using paper-button-behavior as an example. See below.

```
<!--
@license
Copyright (c) 2015 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
-->

<link rel="import" href="../polymer/polymer.html">
<link rel="import" href="../iron-behaviors/iron-button-state.html">

<script>

  /** @polymerBehavior */
  Polymer.PaperRadioButtonInk = {

    observers: [
      '_focusedChanged(focused)'
    ],

    _focusedChanged: function(focused) {
      if (!this.$.ink)
        return;

      if (focused) {
        var rect = this.$.ink.getBoundingClientRect();
        this.$.ink.downAction();
      } else {
        this.$.ink.upAction();
      }
    }

  };

  /** @polymerBehavior */
  Polymer.PaperRadioButtonBehavior = Polymer.IronButtonState.concat(
    Polymer.IronControlState,
    Polymer.PaperRadioButtonInk
  );

</script>
```

**Comment by chuckh** [comment]
I changed  `Polymer. HighlightBehavior = {` back to  `HighlightBehavior = {`

**Comment by arthurevans** [comment]
Awesome. Yes, that's right. LGTM.

**Pull request merged**
