### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by pensierinmusica**

### CODE REVIEW

**Comment by pensierinmusica** [comment]
Thanks, just signed it.

**Comment by arthurevans** [comment]
Sorry we had to close this PR. We replaced the master branch of the docs repo, with the all-new docs site. Because there's no shared history with the old master branch, the easiest way to get started with the new site is to clone a new repo and follow the install instructions in the [README](https://github.com/Polymer/docs/blob/master/README.md). Thanks for your contribution, and apologies for the inconvenience.

**Comment by pensierinmusica** [comment]
Hi @arthurevans, can you please point me to the correct repo to make the PR then? Thanks!

**Comment by arthurevans** [comment]
Sure. It's the same repo, the issue is that the new master branch is totally different from (and shares no history with) the old master branch.

So the easiest way to do this is to start a whole new local repo with:

```
git clone https://github.com/Polymer/docs --recursive
cd docs
npm install
```

See the [README](https://github.com/Polymer/docs/blob/master/README.md) for instructions on running the site. The README comments were a little out of date (they had the wrong repo name), but they should be updated now.

**Pull request closed without merging**
