### PR TITLE
Update 'Event listener setup' section

### PR DESCRIPTION
**Pull request by rakhmanoff**
Added a description for 'nodeId.eventName' syntax - this usecase is unclear from current docs

### CODE REVIEW

**Comment by volkhv** [comment]
I signed it!

**Comment by ebidel** [comment]
I didn't know this was supported :) cc @arthurevans

**Comment by arthurevans** [comment]
LGTM. Thanks!

**Comment by arthurevans** [comment]
Hi Andrey,

I edited your commit a little bit and added it here:

https://github.com/Polymer/docs/pull/1054

**Pull request merged**
