### PR TITLE
Should include Opera

### PR DESCRIPTION
**Pull request by renfeng**

### CODE REVIEW

**Comment by ebidel** [comment]
Opera uses blink as a rendering engine. So the support is the same as chrome. Let's only include opera if we're filling in the table.

**Comment by ebidel** [comment]
Another point. Opera is < 1.5 market share. May not be worth including

**Comment by renfeng** [comment]
It's noteworthy because of its better support of Polymer than Firefox :)

**Comment by ebidel** [comment]
can you include the versions instead of `"?"`?

**Comment by renfeng** [comment]
Sure!... I'm using Opera 32.0... Look like I need to submit a new patch. (Don't know how to edit this one in place.)

Can you show me how to test the features in the table, so I can verify all my question marks myself? Thanks :)

**Comment by renfeng** [comment]
Opera is listed under Chrome in the same column header here, http://jonrimmer.github.io/are-we-componentized-yet/ - All stable!

**Comment by ebidel** [comment]
Right, but your PR has `<td>?</td>` everywhere.

**Comment by renfeng** [comment]
Let me submit a new PR in a moment.

**Comment by arthurevans** [comment]
Ping. Are you submitting a new PR? Should we close this one?

**Comment by arthurevans** [comment]
Closing as out of date.

**Comment by renfeng** [comment]
Just checked https://www.polymer-project.org with the latest version of Opera for Linux. 

About Opera
Version information
Version
12.16 
Build
1860 
Platform
Linux 
System
x86_64, 3.13.0-37-generic 
Browser identification

Opera/9.80 (X11; Linux x86_64; Edition Linux Mint) Presto/2.12.388 Version/12.16

Sadly found that even the Polymer home page, https://www.polymer-project.org, is not rendered well. The menu on the upper right is missing...

**Pull request closed without merging**
