### PR TITLE
Manage Ruby deps (e.g. Jekyll) with Bundler

### PR DESCRIPTION
**Pull request by ssorallen**
This is a more maintainable way of managing Ruby dependencies for
the site. When prepping to run the site locally, this adds a
`bundle install` step.

* Lock Jekyll to ~>2.4 as noted in the README because the Grunt task
  expects certain files from Jekyll that were moved in 2.5.

[1] http://bundler.io/

### CODE REVIEW

**Comment by robdodson** [comment]
LGTM! @ebidel @arthurevans are you ok with this change? It should make it easier to manage our various ruby deps.

**Comment by ssorallen** [comment]
By the way, I used this to run the site locally rather than copy/paste the `gem install` command that was listed in the README. The site does indeed need Jekyll 2.4.0 (and not 2.5.x).

**Comment by arthurevans** [comment]
Yep, LGTM. Should make it easier for folks to play along at home..

**Comment by addyosmani** [comment]
Changes LGTM too. cc @ebidel on the merge.

**Pull request merged**
