### PR TITLE
Update migration.md

### PR DESCRIPTION
**Pull request by michaelpg**
Event handler parameters changed from 0.5 but this is not documented anywhere.

### CODE REVIEW

**Comment by michaelpg** [comment]
btw, source is https://github.com/Polymer/polymer/blob/fcbb3071bc3194bfd11f9b0d87e17800ad8bbb6c/src/standard/events.html#L62

**Comment by arthurevans** [comment]
LGTM.

**Comment by addyosmani** [comment]
friendly ping @michaelpg

**Comment by michaelpg** [comment]
Couldn't figure out how to update this without my old repo... see #1224. I haven't been able to test that because I'm having issues with the Ruby steps on my new machine.

**Pull request closed without merging**
