### PR TITLE
app-drawer-template to starter-kit

### PR DESCRIPTION
**Pull request by abdonrd**
`app-drawer-template` to `starter-kit`.

### CODE REVIEW

**Comment by robdodson** [comment]
awesome, thank you @abdonrd!

**Comment by abdonrd** [comment]
Your welcome @robdodson!

**Comment by arthurevans** [comment]
LGTM. We may have to tweak the whitespace in the samples later on, but I'd like to get this update out.  (Because people cut&paste code, ideally the indentation in the cut & paste samples matches the places they go in the finished project.)

**Comment by robdodson** [comment]
great thanks @arthurevans !

**Pull request merged**
