### PR TITLE
Fixes #1575, #1574. Minor landing page revamp.

### LINKED ISSUE #1575: Remove Polymer Summit banner from homepage

### PR DESCRIPTION
**Pull request by arthurevans**
@tjsavage a quick stab in the direction of cleaning up the home page.

Staged at: https://new-face-dot-polymer-project.appspot.com/1.0/

Intro needs refreshing, so this is not ready for primetime yet, just experimenting. 
(This is actually the intro from 0.5, but it's closer to what we want than the 1.0 text.)

Other than that, just removed the cruft and shuffled some things around.

Cc: @kaycebasques @ebidel @robdodson

### CODE REVIEW

**Comment by tjsavage** [comment]
Awesome, thanks for taking a look at this. Looking really clean and nice.

A couple little notes so far:

- "Components for the modern web" hangs "web" onto a new line at full width. Maybe update to "Component library for the modern web" ?
- I think we might change the "Use an element from the catalog" line to de-emphasize the Polymer team elements and re-emphasize the broader web component community. Maybe change to "Use an existing element"

**Comment by robdodson** [comment]
It looks like maybe the CSS on the original homepage changed. Our first example (the one with the map) looks scrunched up in this PR as well as on the current home page. The block of code is too wide now for some reason

**Comment by tjsavage** [comment]
Quick bump on this

**Comment by arthurevans** [comment]
I'll try to take a look later in the week. Slammed right now.

Would be happy if anyone has a clue on the CSS.

**Comment by robdodson** [comment]
A little backed up prepping for the event this evening but if someone pokes me tomorrow I will review the heck out of this :D

**Comment by tjsavage** [comment]
Awesome thank you!

**Comment by robdodson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robdodson** [comment]
homepage changes lgtm

**Pull request closed without merging**
