### PR TITLE
Polycast link update

### PR DESCRIPTION
**Pull request by e111077**
I'm the polycast now!

Tangentially I also released a polycast that goes through installing node + polymer CLI + vs code extensions (Will have to make another one for 3.0 when that comes out)

### CODE REVIEW

**Comment by arthurevans** [comment]
LGTM2. But should we maybe add @e111077's name in here too?

**Comment by arthurevans** [comment]
Learn Polymer with Elliott Marquez and Rob Dodson?

**Comment by e111077** [comment]
Rob is bowing out of Polycasts, but he has so far done 63/65 episodes. Perhaps we should also put a reminder to phase it out? Is it okay if we merge this one and I can do that in another PR?

**Comment by e111077** [comment]
see #2488

**Pull request merged**
